// export const API_Law = "http://193.176.243.113/api/law/";
// export const API_Login = "http://193.176.243.113/api/accounts/login/";
// export const API_Register = "http://193.176.243.113/api/accounts/register/";
// export const API_Category_Laws = "http://193.176.243.113/api/law/category/";
// export const API_Category_Tree = "http://193.176.243.113/api/tree/category/";
// export const API_Category_Parent = "http://193.176.243.113/api/parent/category/";
// export const API_Tags = "http://193.176.243.113/api/tag/";
// export const Home = "http://localhost:3000/";
// export const API_Get_Comment = "http://193.176.243.113/api/comment/";
// export const API_Course_List_all = "http://193.176.243.113/api/class/course/";
// export const API_Course_List_id = "http://193.176.243.113/api/class/course/detail/";
// export const API_Class_Comment_id = "http://193.176.243.113/api/class/comment/";
// export const API_Person_Course_list = "http://193.176.243.113/api/class/list/";
// export const API_Register_Course = "http://193.176.243.113/api/class/add/";
// export const API_Verify_Token = "http://193.176.243.113/api/rest-auth/token/verify/";
// export const API_Refresh_Token = "http://193.176.243.113/api/rest-auth/token/refresh/";
// export const API_Check_Login = "http://193.176.243.113/api/accounts/check-auth/";
// export const API_Service_List = "http://193.176.243.113/api/service/list/";
// export const API_Register_Lawyer = "http://193.176.243.113/api/service/lawyer/";
// export const API_Register_Expert = "http://193.176.243.113/api/service/expert/";
// export const API_Completion_Profile = "http://193.176.243.113/api/accounts/profile/"; //need slug//
// export const API_Get_Course_Teachers = "http://193.176.243.113/api/class/teacher/"; //need course id
// export const API_Create_Basket = "http://193.176.243.113/api/class/add/";
// export const API_Payment = "http://193.176.243.113/api/order/submit/";

export const API_Law = "/api/law/";
export const API_Login = "/api/accounts/login/";
export const API_Register = "/api/accounts/register/";
export const API_Category_Laws = "/api/law/category/";
export const API_Category_Tree = "/api/tree/category/";
export const API_Category_Parent = "/api/parent/category/";
export const API_Tags = "/api/tag/";
export const API_Get_Comment = "/api/comment/";
export const API_Course_List_all = "/api/class/course/";
export const API_Course_List_id = "/api/class/course/detail/";
export const API_Class_Comment_id = "/api/class/comment/";
export const API_Person_Course_list = "/api/class/list/";
export const API_Register_Course = "/api/class/add/";
export const API_Verify_Token = "/api/rest-auth/token/verify/";
export const API_Refresh_Token = "/api/rest-auth/token/refresh/";
export const API_Check_Login = "/api/accounts/check-auth/";
export const API_Service_List = "/api/service/list/";
export const API_Register_Lawyer = "/api/service/lawyer/";
export const API_Register_Expert = "/api/service/expert/";
export const API_Completion_Profile = "/api/accounts/profile/"; //need slug//
export const API_Get_Course_Teachers = "/api/class/teacher/"; //need course id
export const API_Create_Basket = "/api/class/add/";
export const API_Payment = "/api/order/submit/";